version: '3.9'
services:
  webserver:
    build:
      context: .
      dockerfile: DockerFile
    image: my_image:latest
    volumes:
      - shared_volume:/home/airflow
    container_name: test_container_test
    ports:
      - 8080:8080
      - 8000:8000
      - 3001:3001
    networks:
      - backend
    restart: always
    depends_on:
      - dataBase
  dataBase:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
     - 5432:5432
    volumes:
      - shared_volume:/home
    networks:
      - backend
networks:
  backend:
    driver: "bridge"
volumes:
  shared_volume:
